// proto/ocap.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pkg/schemas/protobuf/v1/ocap.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNKNOWN EntityType = 0
	EntityType_ENTITY_TYPE_UNIT    EntityType = 1
	EntityType_ENTITY_TYPE_VEHICLE EntityType = 2
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNKNOWN",
		1: "ENTITY_TYPE_UNIT",
		2: "ENTITY_TYPE_VEHICLE",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNKNOWN": 0,
		"ENTITY_TYPE_UNIT":    1,
		"ENTITY_TYPE_VEHICLE": 2,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_schemas_protobuf_v1_ocap_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_pkg_schemas_protobuf_v1_ocap_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{0}
}

type Side int32

const (
	Side_SIDE_UNKNOWN Side = 0
	Side_SIDE_WEST    Side = 1
	Side_SIDE_EAST    Side = 2
	Side_SIDE_GUER    Side = 3
	Side_SIDE_CIV     Side = 4
	Side_SIDE_GLOBAL  Side = 5
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNKNOWN",
		1: "SIDE_WEST",
		2: "SIDE_EAST",
		3: "SIDE_GUER",
		4: "SIDE_CIV",
		5: "SIDE_GLOBAL",
	}
	Side_value = map[string]int32{
		"SIDE_UNKNOWN": 0,
		"SIDE_WEST":    1,
		"SIDE_EAST":    2,
		"SIDE_GUER":    3,
		"SIDE_CIV":     4,
		"SIDE_GLOBAL":  5,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_schemas_protobuf_v1_ocap_proto_enumTypes[1].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_pkg_schemas_protobuf_v1_ocap_proto_enumTypes[1]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{1}
}

// Manifest - loaded once at playback start (~10-100KB)
type Manifest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	WorldName        string                 `protobuf:"bytes,2,opt,name=world_name,json=worldName,proto3" json:"world_name,omitempty"`
	MissionName      string                 `protobuf:"bytes,3,opt,name=mission_name,json=missionName,proto3" json:"mission_name,omitempty"`
	FrameCount       uint32                 `protobuf:"varint,4,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	ChunkSize        uint32                 `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	CaptureDelayMs   uint32                 `protobuf:"varint,6,opt,name=capture_delay_ms,json=captureDelayMs,proto3" json:"capture_delay_ms,omitempty"`
	ChunkCount       uint32                 `protobuf:"varint,7,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Entities         []*EntityDef           `protobuf:"bytes,8,rep,name=entities,proto3" json:"entities,omitempty"`
	Times            []*TimeSample          `protobuf:"bytes,9,rep,name=times,proto3" json:"times,omitempty"`
	Events           []*Event               `protobuf:"bytes,10,rep,name=events,proto3" json:"events,omitempty"`
	Markers          []*MarkerDef           `protobuf:"bytes,11,rep,name=markers,proto3" json:"markers,omitempty"`
	ExtensionVersion string                 `protobuf:"bytes,12,opt,name=extension_version,json=extensionVersion,proto3" json:"extension_version,omitempty"`
	AddonVersion     string                 `protobuf:"bytes,13,opt,name=addon_version,json=addonVersion,proto3" json:"addon_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Manifest) GetWorldName() string {
	if x != nil {
		return x.WorldName
	}
	return ""
}

func (x *Manifest) GetMissionName() string {
	if x != nil {
		return x.MissionName
	}
	return ""
}

func (x *Manifest) GetFrameCount() uint32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *Manifest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Manifest) GetCaptureDelayMs() uint32 {
	if x != nil {
		return x.CaptureDelayMs
	}
	return 0
}

func (x *Manifest) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *Manifest) GetEntities() []*EntityDef {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Manifest) GetTimes() []*TimeSample {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *Manifest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Manifest) GetMarkers() []*MarkerDef {
	if x != nil {
		return x.Markers
	}
	return nil
}

func (x *Manifest) GetExtensionVersion() string {
	if x != nil {
		return x.ExtensionVersion
	}
	return ""
}

func (x *Manifest) GetAddonVersion() string {
	if x != nil {
		return x.AddonVersion
	}
	return ""
}

type EntityDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          EntityType             `protobuf:"varint,2,opt,name=type,proto3,enum=ocap.v1.EntityType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Side          Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=ocap.v1.Side" json:"side,omitempty"`
	GroupName     string                 `protobuf:"bytes,5,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	StartFrame    uint32                 `protobuf:"varint,7,opt,name=start_frame,json=startFrame,proto3" json:"start_frame,omitempty"`
	EndFrame      uint32                 `protobuf:"varint,8,opt,name=end_frame,json=endFrame,proto3" json:"end_frame,omitempty"`
	IsPlayer      bool                   `protobuf:"varint,9,opt,name=is_player,json=isPlayer,proto3" json:"is_player,omitempty"`
	VehicleClass  string                 `protobuf:"bytes,10,opt,name=vehicle_class,json=vehicleClass,proto3" json:"vehicle_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDef) Reset() {
	*x = EntityDef{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDef) ProtoMessage() {}

func (x *EntityDef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDef.ProtoReflect.Descriptor instead.
func (*EntityDef) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{1}
}

func (x *EntityDef) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityDef) GetType() EntityType {
	if x != nil {
		return x.Type
	}
	return EntityType_ENTITY_TYPE_UNKNOWN
}

func (x *EntityDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityDef) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNKNOWN
}

func (x *EntityDef) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *EntityDef) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *EntityDef) GetStartFrame() uint32 {
	if x != nil {
		return x.StartFrame
	}
	return 0
}

func (x *EntityDef) GetEndFrame() uint32 {
	if x != nil {
		return x.EndFrame
	}
	return 0
}

func (x *EntityDef) GetIsPlayer() bool {
	if x != nil {
		return x.IsPlayer
	}
	return false
}

func (x *EntityDef) GetVehicleClass() string {
	if x != nil {
		return x.VehicleClass
	}
	return ""
}

type TimeSample struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FrameNum       uint32                 `protobuf:"varint,1,opt,name=frame_num,json=frameNum,proto3" json:"frame_num,omitempty"`
	SystemTimeUtc  string                 `protobuf:"bytes,2,opt,name=system_time_utc,json=systemTimeUtc,proto3" json:"system_time_utc,omitempty"`
	Date           string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	TimeMultiplier float32                `protobuf:"fixed32,4,opt,name=time_multiplier,json=timeMultiplier,proto3" json:"time_multiplier,omitempty"`
	Time           float32                `protobuf:"fixed32,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimeSample) Reset() {
	*x = TimeSample{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSample) ProtoMessage() {}

func (x *TimeSample) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSample.ProtoReflect.Descriptor instead.
func (*TimeSample) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{2}
}

func (x *TimeSample) GetFrameNum() uint32 {
	if x != nil {
		return x.FrameNum
	}
	return 0
}

func (x *TimeSample) GetSystemTimeUtc() string {
	if x != nil {
		return x.SystemTimeUtc
	}
	return ""
}

func (x *TimeSample) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimeSample) GetTimeMultiplier() float32 {
	if x != nil {
		return x.TimeMultiplier
	}
	return 0
}

func (x *TimeSample) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

// Chunk - loaded on demand (~100KB-1MB each)
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	StartFrame    uint32                 `protobuf:"varint,2,opt,name=start_frame,json=startFrame,proto3" json:"start_frame,omitempty"`
	FrameCount    uint32                 `protobuf:"varint,3,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	Frames        []*Frame               `protobuf:"bytes,4,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chunk) GetStartFrame() uint32 {
	if x != nil {
		return x.StartFrame
	}
	return 0
}

func (x *Chunk) GetFrameCount() uint32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *Chunk) GetFrames() []*Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNum      uint32                 `protobuf:"varint,1,opt,name=frame_num,json=frameNum,proto3" json:"frame_num,omitempty"`
	Entities      []*EntityState         `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{4}
}

func (x *Frame) GetFrameNum() uint32 {
	if x != nil {
		return x.FrameNum
	}
	return 0
}

func (x *Frame) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	PosX          float32                `protobuf:"fixed32,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Direction     uint32                 `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Alive         uint32                 `protobuf:"varint,5,opt,name=alive,proto3" json:"alive,omitempty"`
	CrewIds       []uint32               `protobuf:"varint,6,rep,packed,name=crew_ids,json=crewIds,proto3" json:"crew_ids,omitempty"`
	VehicleId     uint32                 `protobuf:"varint,7,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	IsInVehicle   bool                   `protobuf:"varint,8,opt,name=is_in_vehicle,json=isInVehicle,proto3" json:"is_in_vehicle,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	IsPlayer      bool                   `protobuf:"varint,10,opt,name=is_player,json=isPlayer,proto3" json:"is_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{5}
}

func (x *EntityState) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityState) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *EntityState) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *EntityState) GetDirection() uint32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *EntityState) GetAlive() uint32 {
	if x != nil {
		return x.Alive
	}
	return 0
}

func (x *EntityState) GetCrewIds() []uint32 {
	if x != nil {
		return x.CrewIds
	}
	return nil
}

func (x *EntityState) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *EntityState) GetIsInVehicle() bool {
	if x != nil {
		return x.IsInVehicle
	}
	return false
}

func (x *EntityState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityState) GetIsPlayer() bool {
	if x != nil {
		return x.IsPlayer
	}
	return false
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNum      uint32                 `protobuf:"varint,1,opt,name=frame_num,json=frameNum,proto3" json:"frame_num,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SourceId      uint32                 `protobuf:"varint,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      uint32                 `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Distance      float32                `protobuf:"fixed32,6,opt,name=distance,proto3" json:"distance,omitempty"`
	Weapon        string                 `protobuf:"bytes,7,opt,name=weapon,proto3" json:"weapon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetFrameNum() uint32 {
	if x != nil {
		return x.FrameNum
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *Event) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Event) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

type MarkerDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	StartFrame    uint32                 `protobuf:"varint,3,opt,name=start_frame,json=startFrame,proto3" json:"start_frame,omitempty"`
	EndFrame      uint32                 `protobuf:"varint,4,opt,name=end_frame,json=endFrame,proto3" json:"end_frame,omitempty"`
	PlayerId      int32                  `protobuf:"varint,5,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Side          Side                   `protobuf:"varint,7,opt,name=side,proto3,enum=ocap.v1.Side" json:"side,omitempty"`
	Positions     []*MarkerPosition      `protobuf:"bytes,8,rep,name=positions,proto3" json:"positions,omitempty"`
	Size          []float32              `protobuf:"fixed32,9,rep,packed,name=size,proto3" json:"size,omitempty"`
	Shape         string                 `protobuf:"bytes,10,opt,name=shape,proto3" json:"shape,omitempty"`
	Brush         string                 `protobuf:"bytes,11,opt,name=brush,proto3" json:"brush,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkerDef) Reset() {
	*x = MarkerDef{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerDef) ProtoMessage() {}

func (x *MarkerDef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerDef.ProtoReflect.Descriptor instead.
func (*MarkerDef) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{7}
}

func (x *MarkerDef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MarkerDef) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MarkerDef) GetStartFrame() uint32 {
	if x != nil {
		return x.StartFrame
	}
	return 0
}

func (x *MarkerDef) GetEndFrame() uint32 {
	if x != nil {
		return x.EndFrame
	}
	return 0
}

func (x *MarkerDef) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MarkerDef) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *MarkerDef) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNKNOWN
}

func (x *MarkerDef) GetPositions() []*MarkerPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *MarkerDef) GetSize() []float32 {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *MarkerDef) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *MarkerDef) GetBrush() string {
	if x != nil {
		return x.Brush
	}
	return ""
}

type MarkerPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNum      uint32                 `protobuf:"varint,1,opt,name=frame_num,json=frameNum,proto3" json:"frame_num,omitempty"`
	PosX          float32                `protobuf:"fixed32,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	PosZ          float32                `protobuf:"fixed32,4,opt,name=pos_z,json=posZ,proto3" json:"pos_z,omitempty"`
	Direction     float32                `protobuf:"fixed32,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Alpha         float32                `protobuf:"fixed32,6,opt,name=alpha,proto3" json:"alpha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkerPosition) Reset() {
	*x = MarkerPosition{}
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerPosition) ProtoMessage() {}

func (x *MarkerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerPosition.ProtoReflect.Descriptor instead.
func (*MarkerPosition) Descriptor() ([]byte, []int) {
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP(), []int{8}
}

func (x *MarkerPosition) GetFrameNum() uint32 {
	if x != nil {
		return x.FrameNum
	}
	return 0
}

func (x *MarkerPosition) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *MarkerPosition) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *MarkerPosition) GetPosZ() float32 {
	if x != nil {
		return x.PosZ
	}
	return 0
}

func (x *MarkerPosition) GetDirection() float32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *MarkerPosition) GetAlpha() float32 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

var File_pkg_schemas_protobuf_v1_ocap_proto protoreflect.FileDescriptor

const file_pkg_schemas_protobuf_v1_ocap_proto_rawDesc = "" +
	"\n" +
	"\"pkg/schemas/protobuf/v1/ocap.proto\x12\aocap.v1\"\xf4\x03\n" +
	"\bManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"world_name\x18\x02 \x01(\tR\tworldName\x12!\n" +
	"\fmission_name\x18\x03 \x01(\tR\vmissionName\x12\x1f\n" +
	"\vframe_count\x18\x04 \x01(\rR\n" +
	"frameCount\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\rR\tchunkSize\x12(\n" +
	"\x10capture_delay_ms\x18\x06 \x01(\rR\x0ecaptureDelayMs\x12\x1f\n" +
	"\vchunk_count\x18\a \x01(\rR\n" +
	"chunkCount\x12.\n" +
	"\bentities\x18\b \x03(\v2\x12.ocap.v1.EntityDefR\bentities\x12)\n" +
	"\x05times\x18\t \x03(\v2\x13.ocap.v1.TimeSampleR\x05times\x12&\n" +
	"\x06events\x18\n" +
	" \x03(\v2\x0e.ocap.v1.EventR\x06events\x12,\n" +
	"\amarkers\x18\v \x03(\v2\x12.ocap.v1.MarkerDefR\amarkers\x12+\n" +
	"\x11extension_version\x18\f \x01(\tR\x10extensionVersion\x12#\n" +
	"\raddon_version\x18\r \x01(\tR\faddonVersion\"\xae\x02\n" +
	"\tEntityDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.ocap.v1.EntityTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\x04side\x18\x04 \x01(\x0e2\r.ocap.v1.SideR\x04side\x12\x1d\n" +
	"\n" +
	"group_name\x18\x05 \x01(\tR\tgroupName\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x1f\n" +
	"\vstart_frame\x18\a \x01(\rR\n" +
	"startFrame\x12\x1b\n" +
	"\tend_frame\x18\b \x01(\rR\bendFrame\x12\x1b\n" +
	"\tis_player\x18\t \x01(\bR\bisPlayer\x12#\n" +
	"\rvehicle_class\x18\n" +
	" \x01(\tR\fvehicleClass\"\xa2\x01\n" +
	"\n" +
	"TimeSample\x12\x1b\n" +
	"\tframe_num\x18\x01 \x01(\rR\bframeNum\x12&\n" +
	"\x0fsystem_time_utc\x18\x02 \x01(\tR\rsystemTimeUtc\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12'\n" +
	"\x0ftime_multiplier\x18\x04 \x01(\x02R\x0etimeMultiplier\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x02R\x04time\"\x87\x01\n" +
	"\x05Chunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1f\n" +
	"\vstart_frame\x18\x02 \x01(\rR\n" +
	"startFrame\x12\x1f\n" +
	"\vframe_count\x18\x03 \x01(\rR\n" +
	"frameCount\x12&\n" +
	"\x06frames\x18\x04 \x03(\v2\x0e.ocap.v1.FrameR\x06frames\"V\n" +
	"\x05Frame\x12\x1b\n" +
	"\tframe_num\x18\x01 \x01(\rR\bframeNum\x120\n" +
	"\bentities\x18\x02 \x03(\v2\x14.ocap.v1.EntityStateR\bentities\"\x97\x02\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x13\n" +
	"\x05pos_x\x18\x02 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x03 \x01(\x02R\x04posY\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\rR\tdirection\x12\x14\n" +
	"\x05alive\x18\x05 \x01(\rR\x05alive\x12\x19\n" +
	"\bcrew_ids\x18\x06 \x03(\rR\acrewIds\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\a \x01(\rR\tvehicleId\x12\"\n" +
	"\ris_in_vehicle\x18\b \x01(\bR\visInVehicle\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x1b\n" +
	"\tis_player\x18\n" +
	" \x01(\bR\bisPlayer\"\xc0\x01\n" +
	"\x05Event\x12\x1b\n" +
	"\tframe_num\x18\x01 \x01(\rR\bframeNum\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\rR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\rR\btargetId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x02R\bdistance\x12\x16\n" +
	"\x06weapon\x18\a \x01(\tR\x06weapon\"\xbe\x02\n" +
	"\tMarkerDef\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1f\n" +
	"\vstart_frame\x18\x03 \x01(\rR\n" +
	"startFrame\x12\x1b\n" +
	"\tend_frame\x18\x04 \x01(\rR\bendFrame\x12\x1b\n" +
	"\tplayer_id\x18\x05 \x01(\x05R\bplayerId\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12!\n" +
	"\x04side\x18\a \x01(\x0e2\r.ocap.v1.SideR\x04side\x125\n" +
	"\tpositions\x18\b \x03(\v2\x17.ocap.v1.MarkerPositionR\tpositions\x12\x12\n" +
	"\x04size\x18\t \x03(\x02R\x04size\x12\x14\n" +
	"\x05shape\x18\n" +
	" \x01(\tR\x05shape\x12\x14\n" +
	"\x05brush\x18\v \x01(\tR\x05brush\"\xa0\x01\n" +
	"\x0eMarkerPosition\x12\x1b\n" +
	"\tframe_num\x18\x01 \x01(\rR\bframeNum\x12\x13\n" +
	"\x05pos_x\x18\x02 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x03 \x01(\x02R\x04posY\x12\x13\n" +
	"\x05pos_z\x18\x04 \x01(\x02R\x04posZ\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x02R\tdirection\x12\x14\n" +
	"\x05alpha\x18\x06 \x01(\x02R\x05alpha*T\n" +
	"\n" +
	"EntityType\x12\x17\n" +
	"\x13ENTITY_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10ENTITY_TYPE_UNIT\x10\x01\x12\x17\n" +
	"\x13ENTITY_TYPE_VEHICLE\x10\x02*d\n" +
	"\x04Side\x12\x10\n" +
	"\fSIDE_UNKNOWN\x10\x00\x12\r\n" +
	"\tSIDE_WEST\x10\x01\x12\r\n" +
	"\tSIDE_EAST\x10\x02\x12\r\n" +
	"\tSIDE_GUER\x10\x03\x12\f\n" +
	"\bSIDE_CIV\x10\x04\x12\x0f\n" +
	"\vSIDE_GLOBAL\x10\x05B.Z,github.com/OCAP2/web/pkg/schemas/protobuf/v1b\x06proto3"

var (
	file_pkg_schemas_protobuf_v1_ocap_proto_rawDescOnce sync.Once
	file_pkg_schemas_protobuf_v1_ocap_proto_rawDescData []byte
)

func file_pkg_schemas_protobuf_v1_ocap_proto_rawDescGZIP() []byte {
	file_pkg_schemas_protobuf_v1_ocap_proto_rawDescOnce.Do(func() {
		file_pkg_schemas_protobuf_v1_ocap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_schemas_protobuf_v1_ocap_proto_rawDesc), len(file_pkg_schemas_protobuf_v1_ocap_proto_rawDesc)))
	})
	return file_pkg_schemas_protobuf_v1_ocap_proto_rawDescData
}

var file_pkg_schemas_protobuf_v1_ocap_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_schemas_protobuf_v1_ocap_proto_goTypes = []any{
	(EntityType)(0),        // 0: ocap.v1.EntityType
	(Side)(0),              // 1: ocap.v1.Side
	(*Manifest)(nil),       // 2: ocap.v1.Manifest
	(*EntityDef)(nil),      // 3: ocap.v1.EntityDef
	(*TimeSample)(nil),     // 4: ocap.v1.TimeSample
	(*Chunk)(nil),          // 5: ocap.v1.Chunk
	(*Frame)(nil),          // 6: ocap.v1.Frame
	(*EntityState)(nil),    // 7: ocap.v1.EntityState
	(*Event)(nil),          // 8: ocap.v1.Event
	(*MarkerDef)(nil),      // 9: ocap.v1.MarkerDef
	(*MarkerPosition)(nil), // 10: ocap.v1.MarkerPosition
}
var file_pkg_schemas_protobuf_v1_ocap_proto_depIdxs = []int32{
	3,  // 0: ocap.v1.Manifest.entities:type_name -> ocap.v1.EntityDef
	4,  // 1: ocap.v1.Manifest.times:type_name -> ocap.v1.TimeSample
	8,  // 2: ocap.v1.Manifest.events:type_name -> ocap.v1.Event
	9,  // 3: ocap.v1.Manifest.markers:type_name -> ocap.v1.MarkerDef
	0,  // 4: ocap.v1.EntityDef.type:type_name -> ocap.v1.EntityType
	1,  // 5: ocap.v1.EntityDef.side:type_name -> ocap.v1.Side
	6,  // 6: ocap.v1.Chunk.frames:type_name -> ocap.v1.Frame
	7,  // 7: ocap.v1.Frame.entities:type_name -> ocap.v1.EntityState
	1,  // 8: ocap.v1.MarkerDef.side:type_name -> ocap.v1.Side
	10, // 9: ocap.v1.MarkerDef.positions:type_name -> ocap.v1.MarkerPosition
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_schemas_protobuf_v1_ocap_proto_init() }
func file_pkg_schemas_protobuf_v1_ocap_proto_init() {
	if File_pkg_schemas_protobuf_v1_ocap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_schemas_protobuf_v1_ocap_proto_rawDesc), len(file_pkg_schemas_protobuf_v1_ocap_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_schemas_protobuf_v1_ocap_proto_goTypes,
		DependencyIndexes: file_pkg_schemas_protobuf_v1_ocap_proto_depIdxs,
		EnumInfos:         file_pkg_schemas_protobuf_v1_ocap_proto_enumTypes,
		MessageInfos:      file_pkg_schemas_protobuf_v1_ocap_proto_msgTypes,
	}.Build()
	File_pkg_schemas_protobuf_v1_ocap_proto = out.File
	file_pkg_schemas_protobuf_v1_ocap_proto_goTypes = nil
	file_pkg_schemas_protobuf_v1_ocap_proto_depIdxs = nil
}
