// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Addon struct {
	ID         int64              `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt  pgtype.Timestamptz `json:"deletedAt"`
	Name       pgtype.Text        `json:"name"`
	WorkshopID pgtype.Text        `json:"workshopId"`
}

type AfterActionReview struct {
	ID           int64              `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt    pgtype.Timestamptz `json:"deletedAt"`
	MissionID    pgtype.Int8        `json:"missionId"`
	Author       pgtype.Text        `json:"author"`
	Rating       pgtype.Numeric     `json:"rating"`
	CommentGood  pgtype.Text        `json:"commentGood"`
	CommentBad   pgtype.Text        `json:"commentBad"`
	CommentOther pgtype.Text        `json:"commentOther"`
}

type ChatEvent struct {
	ID           int64              `json:"id"`
	Time         pgtype.Timestamptz `json:"time"`
	MissionID    pgtype.Int8        `json:"missionId"`
	SoldierID    pgtype.Int8        `json:"soldierId"`
	CaptureFrame pgtype.Int8        `json:"captureFrame"`
	Channel      pgtype.Text        `json:"channel"`
	FromName     pgtype.Text        `json:"fromName"`
	SenderName   pgtype.Text        `json:"senderName"`
	Message      pgtype.Text        `json:"message"`
	PlayerUid    pgtype.Text        `json:"playerUid"`
}

type FiredEvent struct {
	ID                int64              `json:"id"`
	Time              pgtype.Timestamptz `json:"time"`
	MissionID         pgtype.Int8        `json:"missionId"`
	SoldierID         pgtype.Int8        `json:"soldierId"`
	CaptureFrame      pgtype.Int8        `json:"captureFrame"`
	Weapon            pgtype.Text        `json:"weapon"`
	Magazine          pgtype.Text        `json:"magazine"`
	FiringMode        pgtype.Text        `json:"firingMode"`
	StartPosition     pgtype.Point       `json:"startPosition"`
	StartElevationAsl pgtype.Numeric     `json:"startElevationAsl"`
	EndPosition       pgtype.Point       `json:"endPosition"`
	EndElevationAsl   pgtype.Numeric     `json:"endElevationAsl"`
}

type GeneralEvent struct {
	ID           int64              `json:"id"`
	Time         pgtype.Timestamptz `json:"time"`
	MissionID    pgtype.Int8        `json:"missionId"`
	CaptureFrame pgtype.Int8        `json:"captureFrame"`
	Name         pgtype.Text        `json:"name"`
	Message      pgtype.Text        `json:"message"`
	ExtraData    []byte             `json:"extraData"`
}

type HitEvent struct {
	ID               int64              `json:"id"`
	Time             pgtype.Timestamptz `json:"time"`
	MissionID        pgtype.Int8        `json:"missionId"`
	CaptureFrame     pgtype.Int8        `json:"captureFrame"`
	VictimIDSoldier  pgtype.Int8        `json:"victimIdSoldier"`
	VictimIDVehicle  pgtype.Int8        `json:"victimIdVehicle"`
	ShooterIDSoldier pgtype.Int8        `json:"shooterIdSoldier"`
	ShooterIDVehicle pgtype.Int8        `json:"shooterIdVehicle"`
	EventText        pgtype.Text        `json:"eventText"`
	Distance         pgtype.Numeric     `json:"distance"`
}

type KillEvent struct {
	ID              int64              `json:"id"`
	Time            pgtype.Timestamptz `json:"time"`
	MissionID       pgtype.Int8        `json:"missionId"`
	CaptureFrame    pgtype.Int8        `json:"captureFrame"`
	VictimIDSoldier pgtype.Int8        `json:"victimIdSoldier"`
	VictimIDVehicle pgtype.Int8        `json:"victimIdVehicle"`
	KillerIDSoldier pgtype.Int8        `json:"killerIdSoldier"`
	KillerIDVehicle pgtype.Int8        `json:"killerIdVehicle"`
	EventText       pgtype.Text        `json:"eventText"`
	Distance        pgtype.Numeric     `json:"distance"`
}

type Mission struct {
	ID                           int64              `json:"id"`
	CreatedAt                    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                    pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt                    pgtype.Timestamptz `json:"deletedAt"`
	MissionName                  pgtype.Text        `json:"missionName"`
	BriefingName                 pgtype.Text        `json:"briefingName"`
	MissionNameSource            pgtype.Text        `json:"missionNameSource"`
	OnLoadName                   pgtype.Text        `json:"onLoadName"`
	Author                       pgtype.Text        `json:"author"`
	ServerName                   pgtype.Text        `json:"serverName"`
	ServerProfile                pgtype.Text        `json:"serverProfile"`
	StartTime                    pgtype.Timestamptz `json:"startTime"`
	WorldID                      pgtype.Int8        `json:"worldId"`
	CaptureDelay                 pgtype.Numeric     `json:"captureDelay"`
	AddonVersion                 pgtype.Text        `json:"addonVersion"`
	ExtensionVersion             pgtype.Text        `json:"extensionVersion"`
	ExtensionBuild               pgtype.Text        `json:"extensionBuild"`
	OcapRecorderExtensionVersion pgtype.Text        `json:"ocapRecorderExtensionVersion"`
	Tag                          pgtype.Text        `json:"tag"`
}

type MissionAddon struct {
	AddonID   int64 `json:"addonId"`
	MissionID int64 `json:"missionId"`
}

type OcapInfo struct {
	ID               int64              `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt        pgtype.Timestamptz `json:"deletedAt"`
	GroupName        pgtype.Text        `json:"groupName"`
	GroupDescription pgtype.Text        `json:"groupDescription"`
	GroupWebsite     pgtype.Text        `json:"groupWebsite"`
	GroupLogo        pgtype.Text        `json:"groupLogo"`
}

type OcapPerformance struct {
	Time                      pgtype.Timestamptz `json:"time"`
	MissionID                 pgtype.Int8        `json:"missionId"`
	BufferSoldiers            pgtype.Int4        `json:"bufferSoldiers"`
	BufferVehicles            pgtype.Int4        `json:"bufferVehicles"`
	BufferSoldierStates       pgtype.Int4        `json:"bufferSoldierStates"`
	BufferVehicleStates       pgtype.Int4        `json:"bufferVehicleStates"`
	BufferGeneralEvents       pgtype.Int4        `json:"bufferGeneralEvents"`
	BufferHitEvents           pgtype.Int4        `json:"bufferHitEvents"`
	BufferKillEvents          pgtype.Int4        `json:"bufferKillEvents"`
	BufferFiredEvents         pgtype.Int4        `json:"bufferFiredEvents"`
	BufferChatEvents          pgtype.Int4        `json:"bufferChatEvents"`
	BufferRadioEvents         pgtype.Int4        `json:"bufferRadioEvents"`
	BufferServerFpsEvents     pgtype.Int4        `json:"bufferServerFpsEvents"`
	WritequeueSoldiers        pgtype.Int4        `json:"writequeueSoldiers"`
	WritequeueVehicles        pgtype.Int4        `json:"writequeueVehicles"`
	WritequeueSoldierStates   pgtype.Int4        `json:"writequeueSoldierStates"`
	WritequeueVehicleStates   pgtype.Int4        `json:"writequeueVehicleStates"`
	WritequeueGeneralEvents   pgtype.Int4        `json:"writequeueGeneralEvents"`
	WritequeueHitEvents       pgtype.Int4        `json:"writequeueHitEvents"`
	WritequeueKillEvents      pgtype.Int4        `json:"writequeueKillEvents"`
	WritequeueFiredEvents     pgtype.Int4        `json:"writequeueFiredEvents"`
	WritequeueChatEvents      pgtype.Int4        `json:"writequeueChatEvents"`
	WritequeueRadioEvents     pgtype.Int4        `json:"writequeueRadioEvents"`
	WritequeueServerFpsEvents pgtype.Int4        `json:"writequeueServerFpsEvents"`
	LastWriteDurationMs       pgtype.Numeric     `json:"lastWriteDurationMs"`
}

type RadioEvent struct {
	ID           int64              `json:"id"`
	Time         pgtype.Timestamptz `json:"time"`
	MissionID    pgtype.Int8        `json:"missionId"`
	SoldierID    pgtype.Int8        `json:"soldierId"`
	CaptureFrame pgtype.Int8        `json:"captureFrame"`
	Radio        pgtype.Text        `json:"radio"`
	RadioType    pgtype.Text        `json:"radioType"`
	StartEnd     pgtype.Text        `json:"startEnd"`
	Channel      pgtype.Int2        `json:"channel"`
	IsAdditional pgtype.Bool        `json:"isAdditional"`
	Frequency    pgtype.Numeric     `json:"frequency"`
	Code         pgtype.Text        `json:"code"`
}

type ServerFpsEvent struct {
	Time         pgtype.Timestamptz `json:"time"`
	MissionID    pgtype.Int8        `json:"missionId"`
	CaptureFrame pgtype.Int8        `json:"captureFrame"`
	FpsAverage   pgtype.Numeric     `json:"fpsAverage"`
	FpsMin       pgtype.Numeric     `json:"fpsMin"`
}

type Soldier struct {
	ID              int64              `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt       pgtype.Timestamptz `json:"deletedAt"`
	MissionID       pgtype.Int8        `json:"missionId"`
	JoinTime        pgtype.Timestamptz `json:"joinTime"`
	JoinFrame       pgtype.Int8        `json:"joinFrame"`
	OcapID          pgtype.Int4        `json:"ocapId"`
	OcapType        pgtype.Text        `json:"ocapType"`
	UnitName        pgtype.Text        `json:"unitName"`
	GroupID         pgtype.Text        `json:"groupId"`
	Side            pgtype.Text        `json:"side"`
	IsPlayer        pgtype.Bool        `json:"isPlayer"`
	RoleDescription pgtype.Text        `json:"roleDescription"`
	PlayerUid       pgtype.Text        `json:"playerUid"`
	ClassName       pgtype.Text        `json:"className"`
	DisplayName     pgtype.Text        `json:"displayName"`
}

type SoldierState struct {
	ID                  int64              `json:"id"`
	Time                pgtype.Timestamptz `json:"time"`
	MissionID           pgtype.Int8        `json:"missionId"`
	CaptureFrame        pgtype.Int8        `json:"captureFrame"`
	SoldierID           pgtype.Int8        `json:"soldierId"`
	Position            pgtype.Point       `json:"position"`
	ElevationAsl        pgtype.Numeric     `json:"elevationAsl"`
	Bearing             pgtype.Int4        `json:"bearing"`
	Lifestate           pgtype.Int2        `json:"lifestate"`
	InVehicle           pgtype.Bool        `json:"inVehicle"`
	VehicleRole         pgtype.Text        `json:"vehicleRole"`
	UnitName            pgtype.Text        `json:"unitName"`
	IsPlayer            pgtype.Bool        `json:"isPlayer"`
	CurrentRole         pgtype.Text        `json:"currentRole"`
	HasStableVitals     pgtype.Bool        `json:"hasStableVitals"`
	IsDraggedCarried    pgtype.Bool        `json:"isDraggedCarried"`
	ScoresInfantryKills pgtype.Int2        `json:"scoresInfantryKills"`
	ScoresVehicleKills  pgtype.Int2        `json:"scoresVehicleKills"`
	ScoresArmorKills    pgtype.Int2        `json:"scoresArmorKills"`
	ScoresAirKills      pgtype.Int2        `json:"scoresAirKills"`
	ScoresDeaths        pgtype.Int2        `json:"scoresDeaths"`
	ScoresTotalScore    pgtype.Int2        `json:"scoresTotalScore"`
}

type Vehicle struct {
	ID            int64              `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt     pgtype.Timestamptz `json:"deletedAt"`
	MissionID     pgtype.Int8        `json:"missionId"`
	JoinTime      pgtype.Timestamptz `json:"joinTime"`
	JoinFrame     pgtype.Int8        `json:"joinFrame"`
	OcapID        pgtype.Int4        `json:"ocapId"`
	OcapType      pgtype.Text        `json:"ocapType"`
	ClassName     pgtype.Text        `json:"className"`
	DisplayName   pgtype.Text        `json:"displayName"`
	Customization pgtype.Text        `json:"customization"`
}

type VehicleState struct {
	ID           int64              `json:"id"`
	Time         pgtype.Timestamptz `json:"time"`
	MissionID    pgtype.Int8        `json:"missionId"`
	CaptureFrame pgtype.Int8        `json:"captureFrame"`
	VehicleID    pgtype.Int8        `json:"vehicleId"`
	Position     pgtype.Point       `json:"position"`
	ElevationAsl pgtype.Numeric     `json:"elevationAsl"`
	Bearing      pgtype.Int4        `json:"bearing"`
	IsAlive      pgtype.Bool        `json:"isAlive"`
	Crew         pgtype.Text        `json:"crew"`
	Fuel         pgtype.Numeric     `json:"fuel"`
	Damage       pgtype.Numeric     `json:"damage"`
	Locked       pgtype.Bool        `json:"locked"`
	EngineOn     pgtype.Bool        `json:"engineOn"`
	Side         pgtype.Text        `json:"side"`
}

type World struct {
	ID                int64              `json:"id"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt         pgtype.Timestamptz `json:"deletedAt"`
	Author            pgtype.Text        `json:"author"`
	WorkshopID        pgtype.Text        `json:"workshopId"`
	DisplayName       pgtype.Text        `json:"displayName"`
	WorldName         pgtype.Text        `json:"worldName"`
	WorldNameOriginal pgtype.Text        `json:"worldNameOriginal"`
	WorldSize         pgtype.Numeric     `json:"worldSize"`
	Location          pgtype.Point       `json:"location"`
}
