name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (!github.event.pull_request.draft && !contains(github.event.pull_request.title, 'WIP'))

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run tests
        run: |
          mkdir -p "$GOTMPDIR"
          go test -coverprofile=cover.out -coverpkg=./cmd/...,./internal/... ./...
        env:
          GOTMPDIR: ${{ runner.temp }}/go-work
          TMPDIR: ${{ runner.temp }}

      - name: Build
        run: go build -o ocap-webserver ./cmd/ocap-webserver

      - name: Archive code coverage results
        uses: actions/upload-artifact@v6
        with:
          name: code-coverage
          path: cover.out

      - name: Download artifact (main.breakdown)
        id: download-main-breakdown
        uses: dawidd6/action-download-artifact@v14
        if: github.event_name == 'pull_request'
        with:
          branch: main
          workflow_conclusion: success
          name: main.breakdown
          if_no_artifact_found: warn

      - name: Check test coverage
        id: coverage
        uses: vladopajic/go-test-coverage/action/source@v2
        with:
          profile: cover.out
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
          breakdown-file-name: ${{ github.ref_name == 'main' && 'main.breakdown' || '' }}
          diff-base-breakdown-file-name: ${{ steps.download-main-breakdown.outputs.found_artifact == 'true' && 'main.breakdown' || '' }}

      - name: Upload artifact (main.breakdown)
        uses: actions/upload-artifact@v6
        if: github.ref_name == 'main'
        with:
          name: main.breakdown
          path: main.breakdown
          if-no-files-found: error

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      actions: read
      pull-requests: write

    steps:
      - uses: fgrosse/go-coverage-report@v1.2.0
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "cover.out"
